apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver-rc
spec:
  replicas: 1
  selector:
    app: webserver
    status: serving
  template:
    metadata:
      labels:
        app: webserver
        guard: pyk
        status: serving
    spec:
      containers:
      - image: nginx:1.9.7
        name: nginx